### ISSUE TITLE
The meaning of CNV types ?

### ISSUE THREAD

**Issue by Chipcui** [mahulchak/svmu#13]
Hi,

Thank you for your SVMU tools. When checking the svmu results of `sv.txt`, I can't understand the meaning of CNV types, such as CNV-Q, CNV-R, nCNV-Q and nCNV-R.

Can you explain the detail meaning of these CNV types?

Thank you in advance!

**Comment by mahulchak** [comment]
Hi,
CNV-Q = more copies in the query genome (query is in the mummer terminology)
CNV-R = more copies in reference
nCNV-Q = >2 copies in query
nCNV-R = >2 copies in reference

**Comment by Chipcui** [comment]
OK. Thank you. 

From Chipcui’s iPhone SE
