### ISSUE TITLE
svmu exit without any error information

### ISSUE THREAD

**Issue by feixue1039** [mahulchak/svmu#3]
HI,
I have a newly assembly plant genome and I'm trying to map it to the reference genome and call large indels. I run the genome comparison with mummer4.0 with the following command:
nucmer -t 25 --mum --noextend -p test  ref.fa sample.fa
Then I run svmu with command:
svmu test.delta ref.fa sample.fa 5 -h
When svmu was writing sv.txt files, it exit without any error message. svmu was run with single thread and 256Gb RAM. 
Is it caused by memory issue?

**Comment by mahulchak** [comment]
I have not tested svmu on mummer 4. It probably does not matter but hard to say. Was anything written to the sv.txt file or the cnv_all.txt file? also, there should not be any - preceding h in svmu command line. only h. If sv.txt file was written, it is unlikely to be a memory issue.

**Comment by feixue1039** [comment]
I think mummer4.0 works as well as Mummer3.23. Because I tried again with only one chromosome this time, it run smoothly to the end, except that cords.txt and indel.txt file are empty.

Yes, the sv.txt is not empty. svmu exit when processing Chr06. But it is only 50Mb in size.

**Comment by mahulchak** [comment]
Are you using the latest code? Do you get a core dump file when the program exits?

**Comment by mahulchak** [comment]
Also, if you are not interested in detecting CNV, then use ‘l’ instead of ‘h’ in svmu command line.

**Comment by feixue1039** [comment]
I git clone the repository and compile svmu on Mar 5, 2018. 
When the program exit, it did not give core dump file.
Yes, I'm only interested in large Indels (>100bp). I will give 'I' a shot. Do you have any suggestions on the cutoff setting?
Thank you very much.

**Comment by mahulchak** [comment]
The latest commit was on March 6 so you could update your code and retry.
Why do you think that the program exit abnormally? I typically use 10-100
as my cutoff value. If you keep getting abnormal exit and you want me to
check the issue, you will have to share the delta file as well as the fasta
files.

**Comment by feixue1039** [comment]
There are 20 chromosomes in the genome and it always exit at Chr06 and there is nothing for Chr07-Chr20 in the sv.txt. So I thought it should be an abnormal exit.

I got the same exit while replace 'h' with 'l'. I will try the latest commit and check if it works.
I could send you the delta file. May I ask what the fasta file for? Do you need to re-align sequences flanking indels to refine breakpoint?

**Comment by mahulchak** [comment]
The fasta files will be used to make sure that the problem is not in the SNP detection part of the program. I can assure you that I will not use your files for anything other than troubleshooting the svmu bug. However, I will understand if you are feeling uncomfortable in sharing the fasta files and don't want to do it :)

**Comment by mahulchak** [comment]
The fasta files are primarily used to identify the SNPs.

**Comment by situssog** [comment]
Hello Mahul,

I wrote before but I'm still having the same problem. Similar to the described here. I'm running svmu in an small genome (13 MB), an the sample is very close related to the reference genome. 

Then have tried several setting and I don't get all chromosomes. I only get SVs for chr I and half of II. 

I also used the last commit again to check if new updates fix the problem, but I get the same. The odd thing is that I only get this problem with this closely related sample. For other more divergent samples I get the correct output with all chromosomes. 

I wonder if you could give it a trial and see if you get the same. 

These are the files I'm using:
https://www.dropbox.com/sh/05qvrfeewomvjtg/AABqAn0ofqQmMi4IhVxmDVTKa?dl=0

Thanks a lot,

Cheers,

/S

**Comment by burnsro** [comment]
Hello, was this resolved. I am also getting this problem aligning the reference genomes of Arabidopsis thaliana and Arabidopsis lyrata. SVMU produves the coords file, but the sv file and cm file are empty.
