### ISSUE TITLE
Does SVMU work with human genome? thanks

### ISSUE THREAD

**Issue by JiguangPeng** [mahulchak/svmu#5]

**Comment by mahulchak** [comment]
I have not tested it on human genome. You can run it and see. you could also try to repeatmask your genome before running svmu on it. There are some issues with highly heterozygous or highly repetitive genomes like maize. I am working on some updates to mitigate them.

**Comment by Jakton** [comment]
I have read the method of the your nature paper.
when should we use mgaps to cluster maximal exact matches before svmu? which is not described here.

**Comment by mahulchak** [comment]
That's the older version. You can find that pipeline here:
https://github.com/mahulchak/svmu/tree/v0.1beta

**Comment by Jakton** [comment]
thank you for the reply. I will try that
