### ISSUE TITLE
segmentation fault (terminated by singal 11)

### ISSUE THREAD

**Issue by cjy8709** [mahulchak/svmu#6]
Hello 

I was interested in using svmu for my genome assembly of interest and I ran into a seg fault error. Could you take a look at this error?
The genome assembly of my organism is a plant ~400Mbp but I hard masked my sample genome and hard masked my reference genome. The reference genome has 12 chromosomes but my sample genome is still a draft so it has ~2000 contigs. I initially thought the seg fault occured due to running out of memory so I just took one chromosome of the ref genome and used numcer to align all of the possible sample genome contigs. I'm running the commands on a server where I gave 140GB of memory and still ran into seg fault error.

Heres what I get with /usr/bin/time -v

> Command terminated by signal 11
>         Command being timed: "/home/PROGRAMS_AND_SCRIPTS/PROGRAMS/svmu/svmu sam2ref.mr.delta RM.chr01.fa sample.fasta 5 h"
>         User time (seconds): 82.17
>         System time (seconds): 6.53
>         Percent of CPU this job got: 89%
>         Elapsed (wall clock) time (h:mm:ss or m:ss): 1:38.90
>         Average shared text size (kbytes): 0
>         Average unshared data size (kbytes): 0
>         Average stack size (kbytes): 0
>         Average total size (kbytes): 0
>         Maximum resident set size (kbytes): 6509976
>         Average resident set size (kbytes): 0
>         Major (requiring I/O) page faults: 0
>         Minor (reclaiming a frame) page faults: 1890746
>         Voluntary context switches: 1553260
>         Involuntary context switches: 900
>         Swaps: 0
>         File system inputs: 0
>         File system outputs: 1880
>         Socket messages sent: 0
>         Socket messages received: 0
>         Signals delivered: 0
>         Page size (bytes): 4096
>         Exit status: 0

And here's what I got from running 

gdb 

> GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
> Copyright (C) 2013 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-redhat-linux-gnu".
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>...
> Reading symbols from /home/PROGRAMS_AND_SCRIPTS/PROGRAMS/svmu/svmu...done.
> [New LWP 4636]
> Core was generated by `/home/PROGRAMS_AND_SCRIPTS/PROGRAMS/svmu/svmu sam2ref.mr.delta /scratch/'.
> Program terminated with signal 11, Segmentation fault.
> #0  0x00002b29496f2fdc in std::string::assign(std::string const&) () from /lib64/libstdc++.so.6
> Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.1.x86_64 libgcc-4.8.5-11.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64
> 

Thanks in advance for the help.

Jae

**Comment by mahulchak** [comment]
I don't think memory is the problem. Will you be able to share your sequences so that I can replicate the error?

**Comment by navajeet123** [comment]
Hi, 
I executed ./svmu sam2ref.mm.delta ref.fasta Scaf.fasta 5 h

It ended with an error msg !
munmap_chunk(): invalid pointer: 0x0000001957d578b0 ***

OutFiles Generated:
trans.txt,  cm.txt, cords.txt(blank)

Can You Please help.
Navajeet

**Comment by mahulchak** [comment]
Sorry somehow I missed this message. Hopefully you were able to find a solution. If there are any outstanding problems, I'll be happy to help. I am closing it for now.
