### ISSUE TITLE
CNV type in sv.txt

### ISSUE THREAD

**Issue by liufy11** [mahulchak/svmu#8]
there are 8 types of CNV in sv.txt namely:CNV-NQ、CNV-NR、CNV-Q、CNV-R、nCNV-NQ、nCNV-NR、nCNV-Q、nCNV-R . Can you tell me what does them mean exactly?

**Comment by mahulchak** [comment]
These are really two types: CNV-Q and CNV-R. CNV-Q means more copies in the query and CNV-R means more copies in reference. you can ignore NR and NQ. nCNV means 3 or more copies. These will eventually be replaced by a consistent nomenclature. Sorry about the confusion.
